export function randomQuote() {
  let min = Math.ceil(1);
  let max = Math.floor(100);
  let num = Math.floor(Math.random() * (max - min + 1) + min);
  let id = "Quote " + num;
  db.collection("Quotes")
    .doc(id)
    .get()
    .then((doc) => {
      console.log(doc.data());
    });
}

export const quote = [
  "Are creeds such simple things like the clothes which a man can change at will and put on at will? Creeds are such for which people live for ages and ages.",
  "Our fathers valued change for the sake of its results we value it in the act.",
  "If the facts don't fit the theory, change the facts.",
  "You are always free to change your mind and choose a different future, or a different past.",
  "Failure is not fatal, but failure to change might be.",
  "We can have no progress without change, whether it be basketball or anything else.",
  "Always Do Your Best. Your best is going to change from moment to moment it will be different when you are healthy as opposed to sick. Under any circumstance, simply do your best, and you will avoid self-judgment, self-abuse and regret.",
  "What is necessary to change a person is to change his awareness of himself.",
  "Goals allow you to control the direction of change in your favor.",
  "Heat of blood makes young people change their inclinations often, and habit makes old ones keep to theirs a great while.",
  "We teach people that they upset themselves. We can't change the past, so we change how people are thinking, feeling and behaving today.",
  "Willingness to change is a strength, even if it means plunging part of the company into total confusion for a while.",
  "Only idiots refuse to change their minds.",
  "When you are young and healthy, it never occurs to you that in a single second your whole life could change.",
  "There are things I can't force. I must adjust. There are times when the greatest change needed is a change of my viewpoint.",
  "Courage is a mean with regard to fear and confidence.",
  "Limits, like fear, is often an illusion.",
  "Fear is stupid. So are regrets.",
  "Fear doesn't exist anywhere except in the mind.",
  "Do the thing you fear to do and keep on doing it... that is the quickest and surest way ever yet discovered to conquer fear.",
  "Live your life that the fear of death can never enter your heart.",
  "It is wisdom in prosperity, when all is as thou wouldn't have it, to fear and suspect the worst.",
  "The groundwork of all happiness is health.",
  "For whatever reason, maybe it's because of my story, but people associate Livestrong with exercise and physical fitness, health and lifestyle choices like that.",
  "The most important quality in a leader is that of being acknowledged as such. All leaders whose fitness is questioned are clearly lacking in force.",
  "I think a basic level of fitness can help the body cope with all manner of incidents.",
  "What then is freedom? The power to live as one wishes.",
  "Who is more to be pitied, a writer bound and gagged by policemen or one living in perfect freedom who has nothing more to say?",
  "True friendship is a plant of slow growth, and must undergo and withstand the shocks of adversity, before it is entitled to the appellation.",
  "Friendship is essentially a partnership.",
  "A friendship that like love is warm A love like friendship, steady.",
  "Learning how to improvise really awakened my interest in music.",
  "Many a man fails as an original thinker simply because his memory it too good.",
  "I look back on my life like a good day's work, it was done and I am satisfied with it.",
  "No evil can happen to a good man, either in life or after death.",
  "Every day is a good day to be alive, whether the sun's shining or not.",
  "Whatever good things we build end up building us.",
  "What is moral is what you feel good after, and what is immoral is what you feel bad after.",
  "Dreams will get you nowhere, a good kick in the pants will take you a long way.",
  "The test of good manners is to be patient with the bad ones.",
  "My New Year's resolution is to stick to a good workout plan that will keep me healthy and happy.",
  "Listen there's a hell of a good universe next door: let's go.",
  "I don't want to be interesting. I want to be good.",
  "A good novel tells us the truth about its hero but a bad novel tells us the truth about its author.",
  "The only good luck many great men ever had was being born with the ability and determination to overcome bad luck.",
  "Fresh air is good if you do not take too much of it most of the achievements and pleasures of life are in bad air.",
  "We must not discriminate between things. Where things are concerned there are no class distinctions. We must pick out what is good for us where we can find it.",
  "It's a good place when all you have is hope and not expectations.",
  "Death and love are the two wings that bear the good man to heaven.",
  "A good garden may have some weeds.",
  "But the real secret to lifelong good health is actually the opposite: Let your body take care of you.",
  "Bear and endure: This sorrow will one day prove to be for your good.",
  "Our doubts are traitors and make us lose the good we oft might win by fearing to attempt.",
  "I believe that every human mind feels pleasure in doing good to another.",
  "Life consists not in holding good cards but in playing those you hold well.",
  "If you pretend to be good, the world takes you very seriously. If you pretend to be bad, it doesn't. Such is the astounding stupidity of optimism.",
  "The World is my country, all mankind are my brethren, and to do good is my religion.",
  "The good ended happily, and the bad unhappily. That is what fiction means.",
  "The only thing to do with good advice is to pass it on. It is never of any use to oneself.",
  "Good habits formed at youth make all the difference.",
  "Many foxes grow gray but few grow good.",
  "If you're not willing to work hard, let someone else do it. I'd rather be with someone who does a horrible job, but gives 110% than with someone who does a good job and gives 60%.",
  "The best preparation for good work tomorrow is to do good work today.",
  "No evil can happen to a good man, either in life or after death.",
  "If you're in a bad situation, don't worry it'll change. If you're in a good situation, don't worry it'll change.",
  "The human body is the best picture of the human soul.",
  "There's a lot of people in this world who spend so much time watching their health that they haven't the time to enjoy it.",
  "Practice puts brains in your muscles.",
  "Muscles come and go flab lasts.",
  "Happiness lies first of all in health.",
  "You change your life by changing your heart.",
  "Life isn't about finding yourself. Life is about creating yourself.",
  "The key to immortality is first living a life worth remembering.",
  "If you ask me what I came into this life to do, I will tell you: I came to live out loud.",
  "Nothing is perfect. Life is messy. Relationships are complex. Outcomes are uncertain. People are irrational.",
  "Life is either a great adventure or nothing.",
  "Life is hard. After all, it kills you.",
  "The goal of life is to make your heartbeat match the beat of the universe, to match your nature with Nature.",
  "Change is upsetting. Repetition is tedious. Three cheers for variation!",
  "Seeing much, suffering much, and studying much, are the three pillars of learning. ",
  "There is moderation even in excess.",
  "Pain is no evil unless it conquers us.",
  "True courage is like a kite a contrary wind raises it higher.",
  "Courage is very important. Like a muscle, it is strengthened by use.",
  "It takes courage to know when you ought to be afraid.",
  "Courage is the fear of being thought a coward.",
  "You don't have to have an attitude if you're famous.",
  "For me, I'd rather have an intense experience than not.",
  "If you learn from defeat, you haven't really lost.",
  "A man can fail many times, but he isn't a failure until he begins to blame somebody else.",
  "I think you can have 10,000 explanations for failure, but no good explanation for success.",
  "Success is not built on success. It's built on failure. It's built on frustration. Sometimes its built on catastrophe.",
  "It is wise to keep in mind that neither success nor failure is ever final.",
  "If at first you don't succeed, failure may be your style.",
  "You always pass failure on your way to success.",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
  "Success is never final, failure is never fatal. It's courage that counts.",
  "There is but one cause of human failure. And that is man's lack of faith in his true Self.",
  "There is no loneliness greater than the loneliness of a failure. The failure is a stranger in his own house.",
  "There are no mistakes, save one: the failure to learn from a mistake.",
];

export const author = [
  "Mahatma Gandhi",
  "Alice Meynell",
  "Albert Einstein",
  "Richard Bach",
  "John Wooden",
  "John Wooden",
  "Miguel Angel Ruiz",
  "Abraham Maslow",
  "Brian Tracy",
  "Francois de La Rochefoucauld",
  "Albert Ellis",
  "Jack Welch",
  "Brigitte Bardot",
  "Annette Funicello",
  "Denis Diderot",
  "Aristotle",
  "Michael Jordan",
  "Marilyn Monroe",
  "Dale Carnegie",
  "Dale Carnegie",
  "Tecumseh",
  "Desiderius Erasmus",
  "Leigh Hunt",
  "Lance Armstrong",
  "Andre Maurois",
  "Richard Hammond",
  "Marcus Tullius Cicero",
  "Kurt Vonnegut",
  "George Washington",
  "Aristotle",
  "Thomas Moore",
  "Carter Burwell",
  "Friedrich Nietzsche",
  "Grandma Moses",
  "Plato",
  "Marty Robbins",
  "Jim Rohn",
  "Ernest Hemingway",
  "Baltasar Gracian",
  "Solomon Ibn Gabirol",
  "James Lafferty",
  "e. e. cummings",
  "Ludwig Mies van der Rohe",
  "Gilbert K. Chesterton",
  "Channing Pollock",
  "Oliver Wendell Holmes",
  "Pablo Picasso",
  "Danny Boyle",
  "Michelangelo",
  "Thomas Fuller",
  "Deepak Chopra",
  "Ovid",
  "William Shakespeare",
  "Thomas Jefferson",
  "Josh Billings",
  "Oscar Wilde",
  "Thomas Paine",
  "Oscar Wilde",
  "Oscar Wilde",
  "Aristotle",
  "Benjamin Franklin",
  "Will Smith",
  "Elbert Hubbard",
  "Plato",
  "John A. Simone, Sr.",
  "Ludwig Wittgenstein",
  "Josh Billings",
  "Sam Snead",
  "Bill Vaughan",
  "George William Curtis",
  "Max Lucado",
  "George Bernard Shaw",
  "Bruce Lee",
  "Emile Zola",
  "Hugh Mackay",
  "Helen Keller",
  "Katharine Hepburn",
  "Joseph Campbell",
  "Mason Cooley",
  "Benjamin Disraeli",
  "Benjamin Disraeli",
  "George Eliot",
  "John Petit-Senn",
  "Ruth Gordon",
  "James A. Michener",
  "Horace Smith",
  "Adriana Lima",
  "Joaquin Phoenix",
  "Zig Ziglar",
  "John Burroughs",
  "Paulo Coelho",
  "Sumner Redstone",
  "Roger Babson",
  "Quentin Crisp",
  "Mickey Rooney",
  "Colin Powell",
  "John Wooden",
  "William James",
  "Eric Hoffer",
  "Robert Fripp",
];
